### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by pvnovarese** [pvnovarese/2023-03-demo#1]
```
details:
  msg: The very ink with which history is written is merely fluid prejudice - Mark Twain
id: 3f43d02832944b84aef072a5ed1be4b1
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2023-03-25T02:48:07.213959'
type: system.test.random_wisdom
```
