### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by pvnovarese** [pvnovarese/2023-03-demo#10]
```
details:
  msg: Moderation is a fatal thing. Nothing succeeds like excess - Oscar Wilde
id: 7010ae127a7a4228bfe05f8a2ce9bcbb
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2023-04-18T17:35:33.655617'
type: system.test.random_wisdom
```
