### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by pvnovarese** [pvnovarese/2023-03-demo#3]
```
details:
  msg: The very ink with which history is written is merely fluid prejudice - Mark Twain
id: 6d537df0eeb5409ab9ac1697e5e9bf24
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2023-03-25T15:37:48.416439'
type: system.test.random_wisdom
```
