### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by pvnovarese** [pvnovarese/2023-03-demo#8]
```
details:
  msg: Against the assault of laughter, nothing can stand - Mark Twain
id: 0b61c8d04fa04b288eae79bcbef99869
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2023-04-18T17:33:08.073334'
type: system.test.random_wisdom
```
