### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by pvnovarese** [pvnovarese/2023-03-demo#9]
```
details:
  msg: All bad poetry springs from genuine feeling - Oscar Wilde
id: 4a858d5144c64459b5364302b1c9cb26
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2023-04-18T17:33:48.231093'
type: system.test.random_wisdom
```
